version: '3.8'

services:
  server:
    # build:
    #   context: ./
    #   target: development-build-stage
    #   dockerfile: Dockerfile
    container_name: server
    image: node:14.14.0
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - pg
    working_dir: /app
    command: 'npm run dev'

  pg:
    image: bitnami/postgresql:11-debian-9
    container_name: pg
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: typeorm
    ports:
      - '5432:5432'

volumes:
  data:
    driver: local
