version: '3.8'

services:
  frontend:
    image: node:14
    container_name: frontend
    volumes:
      - $PWD:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: 'bash -c "npm run start"'
